language: php

php:
  - 5.5

before_script:
  - sudo apt-get install libpcre3 libpcre3-dev
  - composer self-update
  - composer install --no-interaction --prefer-source --dev -vvv
  - mysql -e 'create database edorchestral;'
  - mysql -e 'create database edorchestral_test;'
  - php artisan serve &

script:
  - bin/phpunit
  - bin/codecept run